package netty.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Worker.proto

public final class Data {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ProtocolMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ProtocolMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Beat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Beat_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\014Worker.proto\"\221\001\n\017ProtocolMessage\022#\n\004ty" +
                        "pe\030\001 \001(\0162\025.ProtocolMessage.Type\022\025\n\004beat\030" +
                        "\002 \001(\0132\005.BeatH\000\022\033\n\007message\030\003 \001(\0132\010.Messag" +
                        "eH\000\"\035\n\004Type\022\010\n\004BEAT\020\000\022\013\n\007MESSAGE\020\001B\006\n\004bo" +
                        "dy\"#\n\007Message\022\n\n\002id\030\001 \001(\005\022\014\n\004text\030\002 \001(\t\"" +
                        "\025\n\004Beat\022\r\n\005state\030\001 \001(\005B\010B\004DataH\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_ProtocolMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ProtocolMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ProtocolMessage_descriptor,
                new String[]{"Type", "Beat", "Message", "Body",});
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new String[]{"Id", "Text",});
        internal_static_Beat_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Beat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Beat_descriptor,
                new String[]{"State",});
    }

    private Data() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ProtocolMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ProtocolMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .ProtocolMessage.Type type = 1;</code>
         */
        int getTypeValue();

        /**
         * <code>optional .ProtocolMessage.Type type = 1;</code>
         */
        Data.ProtocolMessage.Type getType();

        /**
         * <code>optional .Beat beat = 2;</code>
         */
        Data.Beat getBeat();

        /**
         * <code>optional .Beat beat = 2;</code>
         */
        Data.BeatOrBuilder getBeatOrBuilder();

        /**
         * <code>optional .Message message = 3;</code>
         */
        Data.Message getMessage();

        /**
         * <code>optional .Message message = 3;</code>
         */
        Data.MessageOrBuilder getMessageOrBuilder();

        public Data.ProtocolMessage.BodyCase getBodyCase();
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>optional string text = 2;</code>
         */
        String getText();

        /**
         * <code>optional string text = 2;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes();
    }

    public interface BeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Beat)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 state = 1;</code>
         */
        int getState();
    }

    /**
     * Protobuf type {@code ProtocolMessage}
     */
    public static final class ProtocolMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ProtocolMessage)
            ProtocolMessageOrBuilder {
        public static final int TYPE_FIELD_NUMBER = 1;
        public static final int BEAT_FIELD_NUMBER = 2;
        public static final int MESSAGE_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:ProtocolMessage)
        private static final Data.ProtocolMessage DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<ProtocolMessage>
                PARSER = new com.google.protobuf.AbstractParser<ProtocolMessage>() {
            public ProtocolMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ProtocolMessage(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Data.ProtocolMessage();
        }

        private int bodyCase_ = 0;
        private Object body_;
        private int type_;

        ;
        private byte memoizedIsInitialized = -1;

        // Use ProtocolMessage.newBuilder() to construct.
        private ProtocolMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ProtocolMessage() {
            type_ = 0;
        }

        private ProtocolMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 18: {
                            Data.Beat.Builder subBuilder = null;
                            if (bodyCase_ == 2) {
                                subBuilder = ((Data.Beat) body_).toBuilder();
                            }
                            body_ =
                                    input.readMessage(Data.Beat.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((Data.Beat) body_);
                                body_ = subBuilder.buildPartial();
                            }
                            bodyCase_ = 2;
                            break;
                        }
                        case 26: {
                            Data.Message.Builder subBuilder = null;
                            if (bodyCase_ == 3) {
                                subBuilder = ((Data.Message) body_).toBuilder();
                            }
                            body_ =
                                    input.readMessage(Data.Message.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((Data.Message) body_);
                                body_ = subBuilder.buildPartial();
                            }
                            bodyCase_ = 3;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Data.internal_static_ProtocolMessage_descriptor;
        }

        public static Data.ProtocolMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.ProtocolMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.ProtocolMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.ProtocolMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.ProtocolMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.ProtocolMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.ProtocolMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Data.ProtocolMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.ProtocolMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.ProtocolMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Data.ProtocolMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Data.ProtocolMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ProtocolMessage> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Data.internal_static_ProtocolMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Data.ProtocolMessage.class, Data.ProtocolMessage.Builder.class);
        }

        public BodyCase
        getBodyCase() {
            return BodyCase.forNumber(
                    bodyCase_);
        }

        /**
         * <code>optional .ProtocolMessage.Type type = 1;</code>
         */
        public int getTypeValue() {
            return type_;
        }

        /**
         * <code>optional .ProtocolMessage.Type type = 1;</code>
         */
        public Data.ProtocolMessage.Type getType() {
            Data.ProtocolMessage.Type result = Data.ProtocolMessage.Type.valueOf(type_);
            return result == null ? Data.ProtocolMessage.Type.UNRECOGNIZED : result;
        }

        /**
         * <code>optional .Beat beat = 2;</code>
         */
        public Data.Beat getBeat() {
            if (bodyCase_ == 2) {
                return (Data.Beat) body_;
            }
            return Data.Beat.getDefaultInstance();
        }

        /**
         * <code>optional .Beat beat = 2;</code>
         */
        public Data.BeatOrBuilder getBeatOrBuilder() {
            if (bodyCase_ == 2) {
                return (Data.Beat) body_;
            }
            return Data.Beat.getDefaultInstance();
        }

        /**
         * <code>optional .Message message = 3;</code>
         */
        public Data.Message getMessage() {
            if (bodyCase_ == 3) {
                return (Data.Message) body_;
            }
            return Data.Message.getDefaultInstance();
        }

        /**
         * <code>optional .Message message = 3;</code>
         */
        public Data.MessageOrBuilder getMessageOrBuilder() {
            if (bodyCase_ == 3) {
                return (Data.Message) body_;
            }
            return Data.Message.getDefaultInstance();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != Data.ProtocolMessage.Type.BEAT.getNumber()) {
                output.writeEnum(1, type_);
            }
            if (bodyCase_ == 2) {
                output.writeMessage(2, (Data.Beat) body_);
            }
            if (bodyCase_ == 3) {
                output.writeMessage(3, (Data.Message) body_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != Data.ProtocolMessage.Type.BEAT.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (bodyCase_ == 2) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, (Data.Beat) body_);
            }
            if (bodyCase_ == 3) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, (Data.Message) body_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Data.ProtocolMessage)) {
                return super.equals(obj);
            }
            Data.ProtocolMessage other = (Data.ProtocolMessage) obj;

            boolean result = true;
            result = result && type_ == other.type_;
            result = result && getBodyCase().equals(
                    other.getBodyCase());
            if (!result) return false;
            switch (bodyCase_) {
                case 2:
                    result = result && getBeat()
                            .equals(other.getBeat());
                    break;
                case 3:
                    result = result && getMessage()
                            .equals(other.getMessage());
                    break;
                case 0:
                default:
            }
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            switch (bodyCase_) {
                case 2:
                    hash = (37 * hash) + BEAT_FIELD_NUMBER;
                    hash = (53 * hash) + getBeat().hashCode();
                    break;
                case 3:
                    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
                    hash = (53 * hash) + getMessage().hashCode();
                    break;
                case 0:
                default:
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ProtocolMessage> getParserForType() {
            return PARSER;
        }

        public Data.ProtocolMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code ProtocolMessage.Type}
         */
        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>BEAT = 0;</code>
             */
            BEAT(0),
            /**
             * <code>MESSAGE = 1;</code>
             */
            MESSAGE(1),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>BEAT = 0;</code>
             */
            public static final int BEAT_VALUE = 0;
            /**
             * <code>MESSAGE = 1;</code>
             */
            public static final int MESSAGE_VALUE = 1;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Type> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.forNumber(number);
                        }
                    };
            private static final Type[] VALUES = values();
            private final int value;

            private Type(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static Type valueOf(int value) {
                return forNumber(value);
            }

            public static Type forNumber(int value) {
                switch (value) {
                    case 0:
                        return BEAT;
                    case 1:
                        return MESSAGE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return Data.ProtocolMessage.getDescriptor().getEnumTypes().get(0);
            }

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:ProtocolMessage.Type)
        }

        public enum BodyCase
                implements com.google.protobuf.Internal.EnumLite {
            BEAT(2),
            MESSAGE(3),
            BODY_NOT_SET(0);
            private final int value;

            private BodyCase(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static BodyCase valueOf(int value) {
                return forNumber(value);
            }

            public static BodyCase forNumber(int value) {
                switch (value) {
                    case 2:
                        return BEAT;
                    case 3:
                        return MESSAGE;
                    case 0:
                        return BODY_NOT_SET;
                    default:
                        return null;
                }
            }

            public int getNumber() {
                return this.value;
            }
        }

        /**
         * Protobuf type {@code ProtocolMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ProtocolMessage)
                Data.ProtocolMessageOrBuilder {
            private int bodyCase_ = 0;
            private Object body_;
            private int type_ = 0;
            private com.google.protobuf.SingleFieldBuilderV3<
                    Beat, Beat.Builder, BeatOrBuilder> beatBuilder_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    Message, Message.Builder, MessageOrBuilder> messageBuilder_;

            // Construct using Data.ProtocolMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Data.internal_static_ProtocolMessage_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Data.internal_static_ProtocolMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Data.ProtocolMessage.class, Data.ProtocolMessage.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = 0;

                bodyCase_ = 0;
                body_ = null;
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Data.internal_static_ProtocolMessage_descriptor;
            }

            public Data.ProtocolMessage getDefaultInstanceForType() {
                return Data.ProtocolMessage.getDefaultInstance();
            }

            public Data.ProtocolMessage build() {
                Data.ProtocolMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Data.ProtocolMessage buildPartial() {
                Data.ProtocolMessage result = new Data.ProtocolMessage(this);
                result.type_ = type_;
                if (bodyCase_ == 2) {
                    if (beatBuilder_ == null) {
                        result.body_ = body_;
                    } else {
                        result.body_ = beatBuilder_.build();
                    }
                }
                if (bodyCase_ == 3) {
                    if (messageBuilder_ == null) {
                        result.body_ = body_;
                    } else {
                        result.body_ = messageBuilder_.build();
                    }
                }
                result.bodyCase_ = bodyCase_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Data.ProtocolMessage) {
                    return mergeFrom((Data.ProtocolMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Data.ProtocolMessage other) {
                if (other == Data.ProtocolMessage.getDefaultInstance()) return this;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                switch (other.getBodyCase()) {
                    case BEAT: {
                        mergeBeat(other.getBeat());
                        break;
                    }
                    case MESSAGE: {
                        mergeMessage(other.getMessage());
                        break;
                    }
                    case BODY_NOT_SET: {
                        break;
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Data.ProtocolMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Data.ProtocolMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            public BodyCase
            getBodyCase() {
                return BodyCase.forNumber(
                        bodyCase_);
            }

            public Builder clearBody() {
                bodyCase_ = 0;
                body_ = null;
                onChanged();
                return this;
            }

            /**
             * <code>optional .ProtocolMessage.Type type = 1;</code>
             */
            public int getTypeValue() {
                return type_;
            }

            /**
             * <code>optional .ProtocolMessage.Type type = 1;</code>
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .ProtocolMessage.Type type = 1;</code>
             */
            public Data.ProtocolMessage.Type getType() {
                Data.ProtocolMessage.Type result = Data.ProtocolMessage.Type.valueOf(type_);
                return result == null ? Data.ProtocolMessage.Type.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .ProtocolMessage.Type type = 1;</code>
             */
            public Builder setType(Data.ProtocolMessage.Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .ProtocolMessage.Type type = 1;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Data.Beat getBeat() {
                if (beatBuilder_ == null) {
                    if (bodyCase_ == 2) {
                        return (Data.Beat) body_;
                    }
                    return Data.Beat.getDefaultInstance();
                } else {
                    if (bodyCase_ == 2) {
                        return beatBuilder_.getMessage();
                    }
                    return Data.Beat.getDefaultInstance();
                }
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Builder setBeat(
                    Data.Beat.Builder builderForValue) {
                if (beatBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    beatBuilder_.setMessage(builderForValue.build());
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Builder setBeat(Data.Beat value) {
                if (beatBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    beatBuilder_.setMessage(value);
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Builder mergeBeat(Data.Beat value) {
                if (beatBuilder_ == null) {
                    if (bodyCase_ == 2 &&
                            body_ != Data.Beat.getDefaultInstance()) {
                        body_ = Data.Beat.newBuilder((Data.Beat) body_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    if (bodyCase_ == 2) {
                        beatBuilder_.mergeFrom(value);
                    }
                    beatBuilder_.setMessage(value);
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Builder clearBeat() {
                if (beatBuilder_ == null) {
                    if (bodyCase_ == 2) {
                        bodyCase_ = 0;
                        body_ = null;
                        onChanged();
                    }
                } else {
                    if (bodyCase_ == 2) {
                        bodyCase_ = 0;
                        body_ = null;
                    }
                    beatBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Data.Beat.Builder getBeatBuilder() {
                return getBeatFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            public Data.BeatOrBuilder getBeatOrBuilder() {
                if ((bodyCase_ == 2) && (beatBuilder_ != null)) {
                    return beatBuilder_.getMessageOrBuilder();
                } else {
                    if (bodyCase_ == 2) {
                        return (Data.Beat) body_;
                    }
                    return Data.Beat.getDefaultInstance();
                }
            }

            /**
             * <code>optional .Beat beat = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    Beat, Beat.Builder, BeatOrBuilder>
            getBeatFieldBuilder() {
                if (beatBuilder_ == null) {
                    if (!(bodyCase_ == 2)) {
                        body_ = Data.Beat.getDefaultInstance();
                    }
                    beatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            Beat, Beat.Builder, BeatOrBuilder>(
                            (Data.Beat) body_,
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                bodyCase_ = 2;
                onChanged();
                ;
                return beatBuilder_;
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Data.Message getMessage() {
                if (messageBuilder_ == null) {
                    if (bodyCase_ == 3) {
                        return (Data.Message) body_;
                    }
                    return Data.Message.getDefaultInstance();
                } else {
                    if (bodyCase_ == 3) {
                        return messageBuilder_.getMessage();
                    }
                    return Data.Message.getDefaultInstance();
                }
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Builder setMessage(
                    Data.Message.Builder builderForValue) {
                if (messageBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    messageBuilder_.setMessage(builderForValue.build());
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Builder setMessage(Data.Message value) {
                if (messageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    messageBuilder_.setMessage(value);
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Builder mergeMessage(Data.Message value) {
                if (messageBuilder_ == null) {
                    if (bodyCase_ == 3 &&
                            body_ != Data.Message.getDefaultInstance()) {
                        body_ = Data.Message.newBuilder((Data.Message) body_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    if (bodyCase_ == 3) {
                        messageBuilder_.mergeFrom(value);
                    }
                    messageBuilder_.setMessage(value);
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Builder clearMessage() {
                if (messageBuilder_ == null) {
                    if (bodyCase_ == 3) {
                        bodyCase_ = 0;
                        body_ = null;
                        onChanged();
                    }
                } else {
                    if (bodyCase_ == 3) {
                        bodyCase_ = 0;
                        body_ = null;
                    }
                    messageBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Data.Message.Builder getMessageBuilder() {
                return getMessageFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            public Data.MessageOrBuilder getMessageOrBuilder() {
                if ((bodyCase_ == 3) && (messageBuilder_ != null)) {
                    return messageBuilder_.getMessageOrBuilder();
                } else {
                    if (bodyCase_ == 3) {
                        return (Data.Message) body_;
                    }
                    return Data.Message.getDefaultInstance();
                }
            }

            /**
             * <code>optional .Message message = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    Message, Message.Builder, MessageOrBuilder>
            getMessageFieldBuilder() {
                if (messageBuilder_ == null) {
                    if (!(bodyCase_ == 3)) {
                        body_ = Data.Message.getDefaultInstance();
                    }
                    messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            Message, Message.Builder, MessageOrBuilder>(
                            (Data.Message) body_,
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                bodyCase_ = 3;
                onChanged();
                ;
                return messageBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:ProtocolMessage)
        }

    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int TEXT_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Message)
        private static final Data.Message DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Data.Message();
        }

        private int id_;
        private volatile Object text_;
        private byte memoizedIsInitialized = -1;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            id_ = 0;
            text_ = "";
        }

        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            text_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Data.internal_static_Message_descriptor;
        }

        public static Data.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Data.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Data.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Data.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Data.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Data.Message.class, Data.Message.Builder.class);
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>optional string text = 2;</code>
         */
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }

        /**
         * <code>optional string text = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Data.Message)) {
                return super.equals(obj);
            }
            Data.Message other = (Data.Message) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getText()
                    .equals(other.getText());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        public Data.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                Data.MessageOrBuilder {
            private int id_;
            private Object text_ = "";

            // Construct using Data.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Data.internal_static_Message_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Data.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Data.Message.class, Data.Message.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0;

                text_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Data.internal_static_Message_descriptor;
            }

            public Data.Message getDefaultInstanceForType() {
                return Data.Message.getDefaultInstance();
            }

            public Data.Message build() {
                Data.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Data.Message buildPartial() {
                Data.Message result = new Data.Message(this);
                result.id_ = id_;
                result.text_ = text_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Data.Message) {
                    return mergeFrom((Data.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Data.Message other) {
                if (other == Data.Message.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Data.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Data.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional string text = 2;</code>
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string text = 2;</code>
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string text = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string text = 2;</code>
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string text = 2;</code>
             */
            public Builder clearText() {

                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

    }

    /**
     * Protobuf type {@code Beat}
     */
    public static final class Beat extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Beat)
            BeatOrBuilder {
        public static final int STATE_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Beat)
        private static final Data.Beat DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Beat>
                PARSER = new com.google.protobuf.AbstractParser<Beat>() {
            public Beat parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Beat(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Data.Beat();
        }

        private int state_;
        private byte memoizedIsInitialized = -1;

        // Use Beat.newBuilder() to construct.
        private Beat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Beat() {
            state_ = 0;
        }

        private Beat(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            state_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Data.internal_static_Beat_descriptor;
        }

        public static Data.Beat parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.Beat parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.Beat parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Data.Beat parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Data.Beat parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.Beat parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.Beat parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Data.Beat parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Data.Beat parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Data.Beat parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Data.Beat prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Data.Beat getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Beat> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Data.internal_static_Beat_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Data.Beat.class, Data.Beat.Builder.class);
        }

        /**
         * <code>optional int32 state = 1;</code>
         */
        public int getState() {
            return state_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (state_ != 0) {
                output.writeInt32(1, state_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (state_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, state_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Data.Beat)) {
                return super.equals(obj);
            }
            Data.Beat other = (Data.Beat) obj;

            boolean result = true;
            result = result && (getState()
                    == other.getState());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + STATE_FIELD_NUMBER;
            hash = (53 * hash) + getState();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Beat> getParserForType() {
            return PARSER;
        }

        public Data.Beat getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Beat}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Beat)
                Data.BeatOrBuilder {
            private int state_;

            // Construct using Data.Beat.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Data.internal_static_Beat_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Data.internal_static_Beat_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Data.Beat.class, Data.Beat.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                state_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Data.internal_static_Beat_descriptor;
            }

            public Data.Beat getDefaultInstanceForType() {
                return Data.Beat.getDefaultInstance();
            }

            public Data.Beat build() {
                Data.Beat result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Data.Beat buildPartial() {
                Data.Beat result = new Data.Beat(this);
                result.state_ = state_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Data.Beat) {
                    return mergeFrom((Data.Beat) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Data.Beat other) {
                if (other == Data.Beat.getDefaultInstance()) return this;
                if (other.getState() != 0) {
                    setState(other.getState());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Data.Beat parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Data.Beat) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional int32 state = 1;</code>
             */
            public int getState() {
                return state_;
            }

            /**
             * <code>optional int32 state = 1;</code>
             */
            public Builder setState(int value) {

                state_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 state = 1;</code>
             */
            public Builder clearState() {

                state_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Beat)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
